# frozen_string_literal: true

source "https://rubygems.org"

gem "activesupport", "~> 7.1"

gem "nokogiri", "~> 1.15"

gem "thor", "~> 1.3"

gem "rspec", "~> 3.12"

gem "byebug", "~> 11.1"

gem "daru", "~> 0.3"
