# frozen_string_literal: true

source "https://rubygems.org"

gem "activesupport", "~> 7.0"

gem "nokogiri", "~> 1.13"

gem "thor", "~> 1.2"

gem "rubytree", "~> 2.0"

gem "daru", "~> 0.3"

gem "rspec", "~> 3.12"

gem "byebug", "~> 11.1"

gem "progress_bar", "~> 1.3"

gem "prime", "~> 0.1.2"
